input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [1, Conv, [3,24,3,2,None,1,"ReLU"]],
        # k s r c
        [1, InvertedResidual, [3, 2, 1, 0.5]], 
        [1, InvertedResidual, [3, 1, 3, 0.5]],
        [1, InvertedResidual, [3, 2, 1, 0.5]],
        [1, InvertedResidual, [3, 1, 7, 0.5]],
        [1, InvertedResidual, [3, 2, 1, 0.5]],
        [1, InvertedResidual, [3, 1, 3, 0.5]],
        
        [1, Conv, [3,1024,3,2,None,1,"ReLU"]],
        [1, GlobalAvgPool, []], #global pool
        [1, Linear, [9]]
    ]